(() => {
  "use strict";

  const STORAGE_KEY = "gravitas-language";
  const clone = value => JSON.parse(JSON.stringify(value));
  const hasPersian = value => /[\u0600-\u06ff]/.test(String(value || ""));

  let language = localStorage.getItem(STORAGE_KEY);
  if (language !== "fa" && language !== "en") language = "en";
  window.GRAVITAS_LANG = language;

  const chapters = {
    fa: [
      { id: "foundation", number: "01", title: "بنیان پروژه", short: "بنیان", icon: "core", description: "چشم‌انداز، مخاطب، نقطه‌ی شروع و شخصیت محتوایی" },
      { id: "youtube", number: "02", title: "یوتیوب", short: "یوتیوب", icon: "youtube", description: "موتور روایت، دیده‌شدن و اعتمادسازی" },
      { id: "website", number: "03", title: "وب‌سایت", short: "وب‌سایت", icon: "web", description: "مرکز عمق، آرشیو، یادگیری و عضویت" },
      { id: "games", number: "04", title: "بازی‌ها", short: "بازی", icon: "game", description: "تجربه‌های تعاملی و امضای Gravitas" },
      { id: "community", number: "05", title: "کامیونیتی", short: "جامعه", icon: "community", description: "نقش‌ها، مشارکت و دلیل بازگشت" },
      { id: "reach", number: "06", title: "رشد و توزیع", short: "رشد", icon: "reach", description: "سیستم انتشار و رسیدن به مخاطب" },
      { id: "revenue", number: "07", title: "مدل درآمدی", short: "درآمد", icon: "pie", description: "پروژه، حمایت، عضویت، لایسنس و محصولات علمی" },
      { id: "research", number: "08", title: "تحقیق و یادگیری", short: "تحقیق", icon: "search", description: "نیازسنجی، بازارسنجی و آزمایش مستمر" },
      { id: "okr", number: "09", title: "OKR و سنجه‌ها", short: "OKR", icon: "chart", description: "Objectiveها، Key Resultها، مایل‌استون‌ها و Gateهای تصمیم" },
      { id: "roadmap", number: "10", title: "رودمپ شش‌ماهه", short: "اجرا", icon: "calendar", description: "فازها، خروجی‌ها و تصویر بلندمدت" }
    ],
    en: [
      { id: "foundation", number: "01", title: "Foundation", short: "Foundation", icon: "core", description: "Vision, audience, starting point, and content personality" },
      { id: "youtube", number: "02", title: "YouTube", short: "YouTube", icon: "youtube", description: "The engine for storytelling, discovery, and trust" },
      { id: "website", number: "03", title: "Website", short: "Website", icon: "web", description: "The home of depth, archives, learning, and membership" },
      { id: "games", number: "04", title: "Games", short: "Games", icon: "game", description: "Interactive experiences and a signature Gravitas format" },
      { id: "community", number: "05", title: "Community", short: "Community", icon: "community", description: "Roles, participation, and reasons to return" },
      { id: "reach", number: "06", title: "Growth & Distribution", short: "Growth", icon: "reach", description: "Publishing system and audience acquisition" },
      { id: "revenue", number: "07", title: "Revenue Model", short: "Revenue", icon: "pie", description: "Projects, sponsorship, membership, licensing, and science products" },
      { id: "research", number: "08", title: "Research & Learning", short: "Research", icon: "search", description: "Needs discovery, market validation, and continuous testing" },
      { id: "okr", number: "09", title: "OKRs & Metrics", short: "OKR", icon: "chart", description: "Objectives, Key Results, milestones, and decision gates" },
      { id: "roadmap", number: "10", title: "Six-Month Roadmap", short: "Execution", icon: "calendar", description: "Phases, outputs, and the long-term direction" }
    ]
  };

  const strings = {
    fa: {
      skip: "رفتن به محتوای سند", goCover: "رفتن به جلد", logoAlt: "لوگوی Gravitas", comments: "نظرها", print: "چاپ یا ذخیره به‌صورت PDF", printTitle: "نسخه‌ی چاپی", index: "فهرست سند", chaptersLabel: "فصل‌های سند", slideControls: "کنترل اسلایدها", previous: "قبلی", next: "بعدی", previousAria: "اسلاید قبلی", nextAria: "اسلاید بعدی", indexTitle: "نقشه‌ی سند", closeIndex: "بستن فهرست", summary1: "۱۰ فصل", summary2: "رسانه + محصول + جامعه", summary3: "تحقیق + OKR + اجرا", arrowHelp: "کلیدهای جهت‌نما برای حرکت", swipeHelp: "اسکرول و Swipe فعال است", commentsTitle: "نظرها و بازخوردها", closeComments: "بستن بخش نظرها", commentsIntro: "این گفت‌وگو برای کل سند است. شماره‌ی اسلاید یا نام فصل را در ابتدای کامنت بنویسید تا بازخورد دقیق‌تر و قابل پیگیری باشد. ثبت نظر با حساب GitHub انجام می‌شود.", commentsFallbackBefore: "اگر ابزار کامنت نمایش داده نشد، ", commentsFallbackLink: "بازخورد را مستقیم در GitHub ثبت کنید", commentsFallbackAfter: ".", noScript: "برای ورق‌زدن این سند، JavaScript را فعال کنید.", sections: "بخش‌ها", fullIndex: "فهرست کامل", menuAria: "نمایش بخش‌های سند", goMenu: "رفتن به منوی بخش‌ها", projectStructure: "ساختار پروژه", slide: "اسلاید", slides: "اسلاید", phaseOutput: "خروجی این فاز", chapter: "فصل", start: "START", chooseSection: "انتخاب بخش", mainMenu: "منوی اصلی", menuTitle: "از کدام بخش شروع کنیم؟", menuLead: "هر فصل یک بخش مستقل از برنامه‌ی Gravitas است. مستقیم وارد موضوع موردنظر شوید یا سند را از ابتدا ورق بزنید.", viewExample: "مشاهده‌ی نمونه", languageTarget: "English", languageCode: "EN"
    },
    en: {
      skip: "Skip to document content", goCover: "Go to cover", logoAlt: "Gravitas logo", comments: "Comments", print: "Print or save as PDF", printTitle: "Print version", index: "Document index", chaptersLabel: "Document chapters", slideControls: "Slide controls", previous: "Previous", next: "Next", previousAria: "Previous slide", nextAria: "Next slide", indexTitle: "Document map", closeIndex: "Close index", summary1: "10 chapters", summary2: "Media + Product + Community", summary3: "Research + OKR + Execution", arrowHelp: "Use arrow keys to navigate", swipeHelp: "Scroll and swipe are enabled", commentsTitle: "Comments & Feedback", closeComments: "Close comments", commentsIntro: "This discussion covers the full document. Start your comment with the slide number or chapter name so feedback is easier to track. Comments are posted with a GitHub account.", commentsFallbackBefore: "If the comments widget does not appear, ", commentsFallbackLink: "submit feedback directly on GitHub", commentsFallbackAfter: ".", noScript: "Enable JavaScript to navigate this document.", sections: "Sections", fullIndex: "Full index", menuAria: "Show document sections", goMenu: "Go to section menu", projectStructure: "Project structure", slide: "slide", slides: "slides", phaseOutput: "Phase output", chapter: "Chapter", start: "START", chooseSection: "Choose a section", mainMenu: "Main menu", menuTitle: "Where should we start?", menuLead: "Each chapter is a self-contained part of the Gravitas plan. Jump directly to a section or move through the document from the beginning.", viewExample: "View example", languageTarget: "فارسی", languageCode: "FA"
    }
  };

  const EN = {
    "GRAVITAS": { lead: "An initial roadmap for building a science media platform, laboratory, and community", note: "English is the primary content language; Persian and other localized editions are added based on audience, topic, and production capacity." },
    "کنجکاوی و توانمندسازی آدم‌ها، نقطه‌ی شروع Gravitas است.": { eyebrow: "01 / Core Idea", title: "Curiosity and empowerment are the starting point for Gravitas.", paragraphs: ["Gravitas is built for people who still have questions—people who want to understand how science works, how it changes the world, and how it is shaped in return by society, philosophy, politics, economics, and technology.", "Empowerment is central to this path. The audience should gain the tools, language, and confidence to ask better questions, test ideas, build their own learning path, and participate in discussion or research.", "YouTube, the website, social platforms, courses, and games are parts of this journey. The center of gravity is the community that gradually forms around Gravitas."], quote: "Curiosity brings people in; empowerment helps them continue and contribute." },
    "یک فضای مشترک برای دو جهان": { eyebrow: "Audience", title: "One shared space for two worlds", lead: "Gravitas creates an accessible entry point for the general public while giving students, researchers, and specialists real tools, learning paths, and ways to contribute.", cards: [{ title: "General audience", text: "Curious people, teachers, students, and science enthusiasts looking for clear stories and tangible experiences." }, { title: "Specialist audience", text: "Students, researchers, scientific programmers, and people in basic sciences and engineering who need tools, analysis, and deeper discussion." }], footer: "Every important topic can have an accessible narrative entry point and a deeper path for those who want more." },
    "AI و ML در پژوهش علمی": { eyebrow: "Starting Point", title: "AI and ML in Scientific Research", paragraphs: ["The field is new and fast-moving, creates broad curiosity, offers direct value to researchers, and naturally connects us to physics, mathematics, computer science, biology, philosophy, and the sociology of science.", "Gravitas should not enter this field by merely listing tools or prompt tricks. The real value begins when we move beyond usage into consequences, limitations, and fundamental questions."] },
    "از ابزار تا مسئله": { eyebrow: "Questions That Shape Identity", title: "From tools to real questions", questions: ["Can artificial intelligence generate scientific hypotheses?", "If a model reaches a result that humans cannot explain, are we still doing science?", "Will the researcher of the future look more like a scientist or a manager of machines?", "Where does AI truly improve research productivity, and where does it only create an illusion of speed?", "Will AI democratize science, or widen the gap between universities and countries?"] },
    "جدی، کنجکاو، روشن و گاهی چالش‌برانگیز": { eyebrow: "Content Personality", title: "Serious, curious, clear—and sometimes challenging", paragraphs: ["Gravitas should not feel like a formal classroom, but scientific accuracy should never be sacrificed for entertainment. Some pieces answer questions, some uncover the right question, and some put real tensions on the table.", "After a strong piece of content, the audience should have something to think about, test, or continue exploring."], cards: [{ title: "Add depth", text: "Reveal the layers and precision behind things that look simple." }, { title: "Make it clear", text: "Make complex ideas understandable without talking down to the audience." }, { title: "Build connections", text: "Connect science with philosophy, society, history, and technology." }, { title: "Create involvement", text: "Move people from watching to thinking, choosing, experimenting, or discussing." }] },
    "جایی که Gravitas دیده و شنیده می‌شود": { title: "Where Gravitas is seen and heard", lead: "YouTube is the main engine for discovery, trust, and establishing the voice of the brand." },
    "یک ایده، یک جهان": { eyebrow: "Program 01", title: "One Idea, One World", lead: "Narrative videos, 8–20 minutes long, built around a scientific concept, theory, or problem—the primary format for deep storytelling.", paragraphs: ["The topic is not merely explained. Its origin story, the people involved, disagreements, failures, and the way it changed how we see the world all become part of the narrative."], bullets: ["Why do physicists still disagree about time?", "Is the universe actually computable?", "What changed when computers entered physics?", "Can a machine truly discover something?", "Why do beautiful theories sometimes turn out to be wrong?"] },
    "شورت‌های یوتیوب": { eyebrow: "Supporting Format / YouTube Shorts", title: "YouTube Shorts", lead: "Short, fast, self-contained videos for reaching new audiences and opening a path into larger questions.", paragraphs: ["Some Shorts come from the main video, while others are written natively for short-form. Every Short should contain a complete idea, a serious question, or a surprising moment—not merely a detached fragment of long-form content."], bullets: ["Scientific questions that can spark curiosity in under a minute", "A short explanation of one concept, chart, experiment, or news item", "Multi-part series that build habit and return visits", "A natural bridge to a long-form video, website dossier, game, or community discussion"] },
    "علم در حال ساخته‌شدن است": { eyebrow: "Program 02", title: "Science in the Making", paragraphs: ["A regular review of scientific news and developments with selective editorial judgment and serious analysis. Instead of listing ten stories, choose two or three that matter, explain the scientific context, and examine how much media hype surrounds them.", "This program can create a dependable rhythm for the channel and give the audience a clear reason to return."] },
    "از نزدیک": { eyebrow: "Program 03", title: "Up Close", lead: "Conversations with researchers, physicists, scientific programmers, philosophers of science, and people working across disciplines.", paragraphs: ["The interview moves beyond a résumé and into the lived reality of scientific work—where failure, uncertainty, boredom, competition, and discovery all coexist."], bullets: ["When was the last time one of your hypotheses turned out to be completely wrong?", "Which part of research is far more tedious than the public imagines?", "Have you ever reached a result you could not explain yourself?", "What does university fail to tell people about science?"] },
    "آزمایشگاه Gravitas": { eyebrow: "Program 04", title: "Gravitas Lab", lead: "Hands-on content about AI, ML, data, simulation, and research tools, with every episode built around a real problem.", bullets: ["Can a simple model predict the behavior of a physical system?", "How can we review a paper with AI without being misled by a wrong answer?", "Can language models detect fabricated sources?", "How should a researcher redesign a daily workflow around new tools?"], footer: "Learning lasts when the audience tries something with their own hands." },
    "میز Gravitas": { eyebrow: "Program 05", title: "The Gravitas Table", lead: "Multi-person discussions around questions that do not have immediate, one-line answers.", bullets: ["Should the use of AI in academic papers be restricted?", "How much should science serve society?", "Does scientific progress always mean human progress?", "Is the university still the best structure for producing knowledge?"], footer: "This format can become one of the main rituals of the community." },
    "جایی که Gravitas عمیق می‌شود": { title: "Where Gravitas goes deeper", lead: "The website is the center for content, experiences, membership, and the continuation of every topic." },
    "هر ویدئو، آغاز یک مسیر": { eyebrow: "Experience Logic", title: "Every video starts a journey", paragraphs: ["After watching a video, the audience enters the website and finds sources, a companion article, charts, simulations, games, comments, discussion, and further reading.", "Content does not end when the video is published. It gains layers on the website, becomes searchable, collects critique and discussion, and connects to collective activity."] },
    "آیا جهان قابل‌محاسبه است؟": { eyebrow: "Example Dossier", title: "Is the universe computable?", items: [{ label: "Article", text: "A fuller version of the story and key concepts" }, { label: "Sources", text: "Primary papers and recommended reading at three levels" }, { label: "Timeline", text: "The history of scientific computing and its turning points" }, { label: "Simulation", text: "A simple, manipulable experience" }, { label: "Viewpoints & comments", text: "Arguments for and against, critiques, and audience perspectives" }, { label: "Community", text: "A weekly question and member discussion" }] },
    "شش فضای اصلی": { eyebrow: "Site Architecture", title: "Six Core Spaces", cards: [{ title: "Magazine", text: "Narrative, analytical, and specialist articles on science, philosophy, and society." }, { title: "Dossiers", text: "Deep collections around a problem, combining video, articles, interviews, games, and events." }, { title: "Interactive Lab", text: "The home of games, simulations, quizzes, and scientific experiences." }, { title: "Newsletter", text: "An editorial selection of the week’s most important ideas and developments—more than a list of links." }, { title: "Learning Paths", text: "Structured paths for AI in research, computational physics, philosophy of science, and paper evaluation." }, { title: "Community", text: "Comments, member profiles, discussions, study groups, events, challenges, and collaborative projects." }] },
    "بازی‌ها، امضای Gravitas": { title: "Games: a Gravitas signature", lead: "For a few minutes, the audience enters the process of scientific thinking: choosing, testing, making mistakes, and seeing consequences." },
    "از مصرف محتوا تا تجربه‌ی علم": { eyebrow: "Why Games?", title: "From consuming content to experiencing science", paragraphs: ["The first games do not need to be large, 3D, or expensive. A short web experience with a precise idea can be educational, memorable, and highly shareable.", "A result, score, thinking profile, or final decision can become part of the growth engine." ] },
    "ماشین فرضیه": { title: "Hypothesis Machine", paragraphs: ["The user receives a phenomenon and a set of data, builds a hypothesis, designs an experiment, and decides what data is needed next.", "The goal is not to find a predetermined answer; the game trains the way a researcher thinks."] },
    "خبر علمی یا هیاهوی رسانه‌ای؟": { title: "Scientific News or Media Hype?", paragraphs: ["The user sees headlines and short news summaries, then decides which conclusions are actually supported by the paper and which were exaggerated on the way through the media."] },
    "بودجه‌ی علم": { title: "The Science Budget", paragraphs: ["The user distributes a limited budget across basic research, medicine, space, the environment, education, and technology. Scientific, economic, and social consequences gradually become visible."] },
    "جهان را تنظیم کن": { title: "Tune the Universe", paragraphs: ["The user changes selected constants or simple rules of a hypothetical universe and observes the effects on stars, matter, and the possibility of life."] },
    "تو داور مقاله‌ای": { title: "You Are the Reviewer", paragraphs: ["A fictional paper is placed in front of the user. They must identify problems in research design, sampling, data analysis, or conclusions."] },
    "آزمایش فکری هفته": { title: "Thought Experiment of the Week", paragraphs: ["Each week, a scientific or philosophical scenario is presented. Members choose, argue for their position, and later the response patterns and reasoning are examined in a video or article."] },
    "جامعه با حضور واقعی ساخته می‌شود": { title: "A community is built through real participation", lead: "A Gravitas member should feel that their contribution is visible and can influence the direction of the project." },
    "تماشاچی تنها نقش موجود نیست": { eyebrow: "Participation Roles", title: "Watching is not the only role", bullets: ["Suggest topics and vote on the next dossier", "Join study groups and online sessions", "Submit questions for guests", "Take part in collaborative experiments", "Recommend projects, papers, or tools", "Write critiques and responses", "Help with translation or content production", "Build games and tools", "Host a discussion or event"], footer: "Roles such as reader, researcher, translator, critic, builder, and host can make participation more visible and meaningful." },
    "رشد و توزیع": { title: "Growth & Distribution", lead: "Gravitas grows through the content itself, networks, search, and experiences that people want to share." },
    "یک موضوع، چند تجربه": { eyebrow: "Publishing System", title: "One Topic, Many Experiences", steps: ["Main YouTube video", "YouTube Shorts and platform-native short clips", "Article and sources", "Chart or infographic", "Interactive question", "Game or quiz", "Community discussion and comments", "Newsletter edition", "Specialist LinkedIn content"], footer: "Each platform receives a version designed for its context; mechanical reposting weakens the identity of the media brand." },
    "هر فضا، یک وظیفه": { eyebrow: "Platform Roles", title: "Every platform has a job", cards: [{ title: "Instagram", text: "Create curiosity through short clips, questions, quizzes, and a low-friction first entry." }, { title: "Telegram", text: "Direct communication with community members, content distribution, and a short newsletter in selected language markets." }, { title: "LinkedIn", text: "Professional credibility and relationships with researchers, universities, and companies." }, { title: "YouTube", text: "Deep storytelling through 8–20 minute videos, discovery through Shorts, and long-term audience relationships." }, { title: "Website", text: "Depth, search, membership, games, and participation." }] },
    "آدم‌ها، جست‌وجو و ابزار": { eyebrow: "Growth Engines", title: "People, search, and tools", paragraphs: ["Collaborations with guests and organizations connect Gravitas to new networks. A shared dossier with a university, scientific society, or specialist community can bring in aligned audiences.", "Topics such as AI in research, research tools, paper evaluation, computational physics, and philosophy of science have strong potential for discovery through Google and YouTube.", "Free games and tools can also create organic growth. Something the audience uses and sends to someone else often has a longer-lasting effect than ordinary advertising."] },

    "مدل درآمدی Gravitas": { title: "The Gravitas Revenue Model", lead: "A blended model that starts with projects and institutional support, gains stability through membership and licensing, and scales through games, science products, and owned intellectual property." },
    "شش مسیر درآمدی مکمل": { eyebrow: "Revenue Engines", title: "Six complementary revenue streams", lead: "No single stream is expected to fund the entire project. Their combination reduces risk and balances the scientific mission with financial sustainability.", cards: [{ title: "Institutional support", text: "Foundations, universities, scientific societies, science centers, and educational institutions support dossiers, games, translation, or science-communication projects." }, { title: "Science projects", text: "Research storytelling, short documentaries, interactive pages, simulations, virtual labs, public reports, and experience design for scientific projects." }, { title: "Companies", text: "Sponsorship, organizational training, specialist content, scientific communication, and CSR projects for technology companies and other industries." }, { title: "Education & membership", text: "Workshops, cohort courses, learning paths, community membership, journal clubs, and access to specialist resources and archives." }, { title: "Games & licensing", text: "Professional game editions, school and university licenses, instructor dashboards, specialist scenarios, and custom game development." }, { title: "Experiment kits & products", text: "Experiment kits, board games, observation and measurement tools, classroom kits, and physical products connected to digital content." }] },
    "سه لایه‌ی درآمد": { eyebrow: "Financial Architecture", title: "Three layers of revenue", lead: "Each layer has a different job: one brings cash in sooner, one creates stability, and one increases the long-term value of the project.", items: [{ label: "Project revenue", text: "Science projects, corporate contracts, organizational training, events, and sponsorship of a specific dossier or product" }, { label: "Recurring revenue", text: "Membership, experiment-kit subscriptions, annual licenses, maintenance contracts, and organizational or university subscriptions" }, { label: "Scalable assets", text: "Games, courses, kits, content formats, the platform, the brand, and Gravitas-owned IP" }] },
    "نهادهای حمایت‌کننده، پروژه‌های علمی و شرکت‌ها": { eyebrow: "B2I + B2B", title: "Institutions, science projects, and companies", cards: [{ title: "Institutions & the science ecosystem", text: "Support for science communication, translation, public access, events, games, and education—alongside projects for universities, laboratories, museums, research institutes, and research teams." }, { title: "Companies & organizations", text: "AI and data literacy training, scientific content, responsible technology communication, interactive experiences, white papers, events, and CSR programs." }], footer: "Financial support must be transparent and must not compromise Gravitas’s scientific or editorial independence." },
    "پک‌های آزمایش؛ علم در دست مخاطب": { eyebrow: "Physical Science Products", title: "Experiment kits: science in the audience’s hands", lead: "A kit is not just a standalone product; it is an entry into a blended experience connecting physical tools, digital content, missions, data collection, and community.", bullets: ["Optics, motion and mechanics, waves and sound, circuits and electronics, astronomy, sensors, or simple robotics kits", "QR links to guides, simulations, games, or related website dossiers", "Observation journals, result logging, data comparison, and staged missions", "Single-experiment editions, topic kits, subscription boxes, and classroom kits", "Custom editions for schools, universities, museums, events, or sponsoring institutions", "Expansion into board games, thought-experiment cards, research journals, and simple scientific tools"] },
    "از درآمد سریع به دارایی مقیاس‌پذیر": { eyebrow: "Execution Order", title: "From fast revenue to scalable assets", lead: "The revenue model is tested in stages so product-development costs do not rise before demand is proven.", items: ["Win science projects and corporate contracts to fund the early stage and learn real market needs", "Run workshops and build a small digital product to test willingness to pay", "Launch membership and the first sellable game or tool", "Build an early experiment-kit prototype and test it with a small group", "Test licensing for schools, universities, or science centers", "Expand the store, product series, and recurring contracts"], outcome: "The long-term goal is to reduce dependence on custom projects and increase the share of membership, licensing, games, and owned products." },

    "چه چیزی را باید بفهمیم؟": { title: "What do we need to understand?", lead: "This chapter should not redefine content, revenue, or execution. Its job is to resolve the unknowns on which Gravitas’s decisions depend." },
    "سؤال اصلی سه ماه اول": { eyebrow: "Central Question", title: "The central question for the first three months", paragraphs: ["Will the audience move from watching a scientific story to taking a scientific action?", "That action could be checking a source, testing a hypothesis, recording data, critiquing an argument, joining a discussion, or contributing to a project."], quote: "Gravitas becomes truly differentiated when people do not only know more—they can ask better questions, test ideas, and contribute." },
    "شش مجهول تصمیم‌ساز": { eyebrow: "Research Map", title: "Six decision-critical unknowns", lead: "Every research activity should turn at least one of these unknowns into a clear decision.", cards: [{ title: "Audience", text: "Exactly who has an unresolved problem and a reason to return?" }, { title: "Need", text: "Where does the audience get stuck when trying to understand, do, or contribute?" }, { title: "Positioning", text: "In a crowded market, what value can Gravitas offer that is both different and credible?" }, { title: "Content & format", text: "Which topic, depth, rhythm, and format create attention, trust, and continuation?" }, { title: "Participation", text: "Which small action genuinely moves someone from watching to active involvement?" }, { title: "Purchase & product", text: "Who allocates money, budget, or sponsorship to which scientific output?" }] },
    "دانسته‌های فعلی را با فرضیه اشتباه نگیریم": { eyebrow: "Known vs Unknown", title: "Do not confuse what we know with what we assume", cards: [{ title: "What desk research shows", text: "English-language science media is competitive, and strong examples already exist in storytelling, depth, interaction, citizen science, and physical products." }, { title: "What still needs to be proven", text: "That this combination creates differentiated value for the Gravitas audience, moves them to action, and is something customers or institutional supporters will buy." }], footer: "Competitors demonstrate that a model is possible; whether that model fits Gravitas still requires behavioral and commercial evidence." },
    "رسانه‌های علمی روایت‌محور": { eyebrow: "Landscape / Story-led Media", title: "Story-led science media", lead: "Examples for studying hooks, brand personality, narrative structure, and the transformation of scientific questions into viewing experiences.", cards: [{ title: "Veritasium", text: "Counterintuitive questions, experiments, interviews, and problem-led storytelling." }, { title: "Kurzgesagt", text: "Compressed storytelling, coherent visual design, and IP that extends beyond video." }, { title: "Vsauce", text: "Starting with a simple question and moving freely across science, philosophy, and culture." }, { title: "SciShow", text: "Regular publishing, broad topic coverage, and turning current science into a followable format." }] },
    "محتوای علمی عمیق و معتبر": { eyebrow: "Landscape / Deep Science", title: "Deep and credible science content", lead: "Examples for studying accuracy, sourcing, explanation of difficult concepts, and long-term trust.", cards: [{ title: "Quanta Magazine", text: "Deep journalism in the fundamental sciences with strong narrative, visuals, and editorial credibility." }, { title: "PBS Space Time", text: "Serious physics and cosmology without removing all complexity." }, { title: "3Blue1Brown", text: "Visualization as part of the mathematical argument itself, not decoration." }, { title: "Numberphile", text: "Simple conversations with experts that turn mathematical ideas into public curiosity." }] },
    "آزمایش، ساختن و مهندسی": { eyebrow: "Landscape / Experiment & Engineering", title: "Experimentation, building, and engineering", lead: "Examples for understanding how observation, failure, building, and visible outcomes make learning memorable.", cards: [{ title: "Mark Rober", text: "Showcase engineering, clear problems, and projects that drive the story forward." }, { title: "Smarter Every Day", text: "Field curiosity, close observation, and learning alongside experts." }, { title: "NileRed", text: "Real laboratory process, methodological detail, and trial-and-error storytelling." }, { title: "Practical Engineering", text: "Explaining everyday engineering systems with models, experiments, and physical demonstrations." }] },
    "یادگیری تعاملی": { eyebrow: "Landscape / Interactive Learning", title: "Interactive learning", lead: "Examples for studying problem-solving, immediate feedback, simulation, and learning paths.", cards: [{ title: "Brilliant", text: "Learning through problem-solving, staged progression, and rapid feedback." }, { title: "PhET", text: "Manipulable science simulations focused on discovering relationships." }, { title: "LabXchange", text: "A combination of educational content, virtual laboratories, and modular learning paths." }, { title: "Khan Academy", text: "Clear instructional structure, practice, assessment, and systematic coverage of fundamentals." }] },
    "علم مشارکتی": { eyebrow: "Landscape / Participatory Science", title: "Participatory science", lead: "Examples that connect audience participation to real data, analysis, or research projects.", cards: [{ title: "Zooniverse", text: "Breaking real research work into tasks that volunteers can perform." }, { title: "SciStarter", text: "Project discovery, onboarding, and pathways into citizen science participation." }, { title: "iNaturalist", text: "Observation logging, collective identification, and scientific data generated from everyday activity." }, { title: "Foldit", text: "Turning a scientific problem into a game and using collective problem-solving." }] },
    "پک آزمایش و محصولات علمی": { eyebrow: "Landscape / Physical Products", title: "Experiment kits and science products", lead: "Examples for studying the connection between content, making, subscriptions, and physical products.", cards: [{ title: "CrunchLabs", text: "Subscription kits, companion videos, and project building around a science creator identity." }, { title: "KiwiCo", text: "Age and topic variety, packaged experiences, and repeat purchase through crates." }, { title: "MEL Science", text: "Topic-based kits paired with digital guidance and staged experiences." }, { title: "Thames & Kosmos", text: "A broad range of STEM kits, detailed manuals, and multi-stage use." }] },
    "درباره‌ی مخاطب چه باید بفهمیم؟": { eyebrow: "Unknown / Audience", title: "What do we need to learn about the audience?", questions: ["Which group has a problem that does not end with one good piece of content and instead requires tools, a path, or a community?", "Where does the audience get stuck between shallow content and academic sources?", "What makes a curious professional or young researcher come back?", "Which markets does English open, and for which groups does it create a barrier?", "What signals make the Gravitas audience trust a scientific source?", "What observable change does empowerment mean from the audience’s own perspective?"] },
    "درباره‌ی محتوا و فرمت چه باید بفهمیم؟": { eyebrow: "Unknown / Content", title: "What do we need to learn about content and format?", questions: ["Which scientific questions have real demand but currently receive answers that are shallow, fragmented, or overly technical?", "Is AI × Research a durable wedge or just a short-term attention wave?", "Which mix of narrative, explanation, interview, and experiment creates the most trust?", "Should Shorts primarily drive discovery, convert viewers to long-form, or stand alone as complete experiences?", "How much depth remains attractive to a general audience, and where does cognitive load become too high?", "Which website continuation after a video creates the most value: sources, tools, simulations, games, or discussion?"] },
    "درباره‌ی حرکت از تماشا به کنش چه باید بفهمیم؟": { eyebrow: "Unknown / Participation", title: "What do we need to learn about moving from watching to action?", questions: ["What is the smallest meaningful action the audience is willing to take?", "Do voting and quizzes lead to deeper participation, or only create shallow engagement?", "Which activities create learning, return visits, or a shared identity?", "Will the audience share their data, reasoning, or experiment outputs with others?", "What feedback is needed for participation to feel seen and valuable?", "When should we move beyond comments and events into a genuinely collaborative project?"] },
    "درباره‌ی خرید، حمایت و محصول چه باید بفهمیم؟": { eyebrow: "Unknown / Buyers & Products", title: "What do we need to learn about buying, sponsorship, and products?", questions: ["Which exact problem has budget inside a university, laboratory, company, or sponsoring institution?", "What deliverable and impact metric does a buyer consider defensible for a science project?", "Which offer can begin with a small sample and a shorter sales cycle?", "Does an experiment kit create more value for personal purchase, classrooms, events, or organizational programs?", "Which physical-product feature is essential: measurement, data, video, community, or reusability?", "What evidence must exist before production to justify manufacturing and logistics costs?"] },
    "جواب‌ها را از کجا به دست می‌آوریم؟": { eyebrow: "Evidence System", title: "Where do the answers come from?", items: [{ label: "Observed behavior", text: "Retention, clicks, experience completion, return visits, and conversion between video, website, and activity." }, { label: "Search demand", text: "Recurring questions, content gaps, audience language, and growing topics." }, { label: "Qualitative conversations", text: "Interviews and observation without a predetermined numerical quota—until decision-relevant patterns become clear." }, { label: "Content experiments", text: "Testing hooks, depth, format, CTA, and interactive continuation with one explicit question per test." }, { label: "Purchase evidence", text: "Meeting requests, proposals, paid pilots, pre-orders, or deposits—not just stated interest." }, { label: "Product experiments", text: "Concept tests, limited prototypes, and observed use before deciding to manufacture." }] },
    "خروجی تحقیق باید چه تصمیم‌هایی بدهد؟": { eyebrow: "Research Output", title: "What decisions should research produce?", bullets: ["The initial audience and its primary problem", "A clear Gravitas position relative to existing alternatives", "The topic wedge and starting format mix", "A measurable path from watching to scientific action", "Priority buyer groups and testable offers", "Continue, change, or stop decisions for each major hypothesis"], quote: "The research chapter is complete when it turns unknowns into decisions—not when it merely produces a long list of competitors and ideas." },

    "OKR شش‌ماهه Gravitas": { title: "Gravitas Six-Month OKRs", lead: "This chapter defines only the outcomes that must be visible by the end of month six. Activities, timing, and the publishing calendar belong in the roadmap chapter." },
    "OKR نتیجه را تعریف می‌کند؛ رودمپ مسیر را": { eyebrow: "OKR vs Roadmap", title: "OKRs define the result; the roadmap defines the path", cards: [{ title: "OKR", text: "Defines what must be proven by the end of six months: content output, an active community, revenue, and an operating system." }, { title: "Roadmap", text: "Defines what happens next, what gets published when, and which cumulative numbers should be reached each month." }], footer: "Monthly activities and publishing dates are not duplicated inside the KRs." },
    "چهار نتیجه‌ای که باید تا پایان ماه ششم ثابت شوند": { eyebrow: "Objectives", title: "Four outcomes that must be proven by the end of month six", cards: [{ title: "O1 — Content engine", text: "Regular production of high-quality English science content in repeatable formats." }, { title: "O2 — Active community", text: "Turn part of the audience into people who return and take meaningful actions." }, { title: "O3 — Revenue model", text: "Prove real willingness to pay across a small number of defensible revenue paths." }, { title: "O4 — Operating system", text: "Build a data-driven process for decisions, production, publishing, and learning." }] },
    "ساختن موتور محتوایی قابل‌تشخیص و تکرار": { eyebrow: "O1 / Content Engine", title: "Build a recognizable, repeatable content engine", bullets: ["12 long-form videos, 8–20 minutes each", "36 YouTube Shorts, with at least 18 designed natively for short-form", "6 companion dossiers or articles on the website", "6 newsletter editions", "2 games, quizzes, simulations, or interactive experiences", "Publish at least 85% of planned outputs on schedule during the final three months", "Improve average retention by at least 20% compared with the first three videos", "Identify three topics or formats performing above the channel median"] },
    "تبدیل مخاطب گذری به جامعه‌ای فعال": { eyebrow: "O2 / Active Community", title: "Turn passing viewers into an active community", bullets: ["1,500 newsletter subscribers", "300 registered members on the website or community space", "100 monthly active members", "250 meaningful contributions during the period", "Four online sessions, study clubs, or live discussions", "Average at least 25 participants per session", "At least 20% 30-day return rate among website users", "30 people contributing through critique, topic suggestions, translation, research, or building"], footer: "An active member is someone who has taken an observable action within the last 30 days; registration alone is not enough." },
    "اعتبارسنجی مدل درآمدی": { eyebrow: "O3 / Revenue Validation", title: "Validate the revenue model", bullets: ["Design and price four clear offers", "Send 12 qualified proposals", "Win at least three paid projects", "Reach at least €15,000 in revenue or signed contracts", "Run one paid workshop with at least 20 participants", "Acquire 50 paid members in the Membership Beta", "Test one experiment kit with genuine purchase or pre-order evidence", "Build one game or tool that can be offered to a school, university, or scientific institution"] },
    "ساختن سیستم اجرایی مبتنی بر داده": { eyebrow: "O4 / Operating System", title: "Build a data-driven operating system", bullets: ["Complete a Decision Document for audience, positioning, and the content wedge", "Maintain an Evidence Map and Source Log for every main video", "Scientific Review for at least 90% of deep content", "Define KPIs for YouTube, website, newsletter, community, and revenue", "Run a weekly data review with continue, change, or stop decisions", "Create a post-mortem for at least 80% of major outputs", "Document 90% of core processes", "Reduce average idea-to-publish production time by 25%"] },
    "توانمندسازی، معیار اصلی رشد": { eyebrow: "North Star + Guardrails", title: "Empowerment is the primary growth metric", items: [{ label: "500 MEP", text: "500 Monthly Empowered Participants by the end of month six—people who have done something deeper than simply watch." }, { label: "Scientific quality", text: "Reliable sourcing for at least 90% of content, transparent disclosure of sponsorship, and correction of reported scientific errors within 72 hours." }, { label: "Focus", text: "At the end of the period, only formats, offers, and products with evidence are selected for scale." }] },

    "برنامه‌ی اجرایی و تقویم انتشار": { title: "Execution Roadmap & Publishing Calendar", lead: "This chapter answers what happens next, how the content calendar is built, what gets published when, and which milestone must be reached each month." },
    "اقدام بعدی؛ چهارده روز تا اولین انتشار": { eyebrow: "Current Sprint", title: "Next action: fourteen days to the first release", lead: "The next phase is not another planning document. It is locking the key decisions and moving the first content cycle from idea to publication.", items: [{ label: "Days 1–2", text: "Confirm the initial audience, the AI × Research wedge, the content promise, and the first six topics." }, { label: "Days 3–5", text: "Build the Evidence Map for episode one, collect primary sources, and select an expert or reviewer." }, { label: "Days 6–8", text: "Write the Content Brief, script, and Scientific Red Team review; design the first Short in parallel." }, { label: "Days 9–11", text: "Shoot, complete the first edit, design the thumbnail, and build the companion website page." }, { label: "Days 12–13", text: "Scientific review, final edit, subtitles, CTA, analytics setup, and release preparation." }, { label: "Day 14", text: "Publish the video, companion Short, and website page; record the baseline for retention, clicks, and audience action." }] },
    "تقویم محتوا چطور ساخته می‌شود؟": { eyebrow: "Calendar Method", title: "How is the content calendar built?", lead: "The calendar does not come from a list of interesting ideas. It comes from the intersection of demand, market gaps, production capacity, and learning goals.", items: [{ label: "1. Collect signals", text: "Search questions, competitor gaps, scientific developments, audience needs, and collaboration opportunities." }, { label: "2. Score topics", text: "Score each topic from 1 to 5 for demand, brand fit, evidence, visual potential, interaction, and production feasibility." }, { label: "3. Choose a portfolio", text: "Select a mix of discoverable topics, deep topics, practical content, and one interactive experiment." }, { label: "4. Write the Content Brief", text: "Define the central question, audience, promise, sources, hook, format, CTA, and success metric." }, { label: "5. Place it in the rhythm", text: "Assign the topic to long-form, Short, dossier, newsletter, or interactive slots based on production time." }, { label: "6. Lock four weeks", text: "The next four weeks are fixed, the following four are prepared, and everything else stays in the backlog." }] },
    "ریتم ثابت انتشار": { eyebrow: "Publishing Cadence", title: "A fixed publishing rhythm", lead: "This cadence is designed for a lean team and directly reaches the KRs of 12 videos, 36 Shorts, 6 dossiers, and 6 newsletters.", cards: [{ title: "Tuesday", text: "One native Short every week: a question, error, claim, or independent Lab Note." }, { title: "Every other Thursday", text: "One main video every two weeks, for a total of two videos per month." }, { title: "Friday of release week", text: "A second Short tied to the main video, plus one question for the website or community." }, { title: "Week without long-form", text: "Website dossier, interactive experiment, interview, or preparation for the next episode." }, { title: "Last Sunday of the month", text: "Monthly newsletter with the best ideas, sources, and results from completed experiments." }, { title: "Weekly review", text: "Monday morning: review data, production status, needed changes, and lock the next week." }] },
    "تقویم انتشار؛ شش هفته‌ی اول": { eyebrow: "12-Week Calendar / Weeks 1–6", title: "Publishing calendar: first six weeks", items: ["Week 1 — Short: Does AI fabricate sources? | Prepare Episode 1 | Set up analytics and the website page template", "Week 2 — Video 01: Can AI generate scientific hypotheses? | Second Short | Source dossier and hypothesis vote", "Week 3 — Short: Guess the Error in a citation | Collect data and write Episode 2", "Week 4 — Video 02: When AI predicts correctly but cannot explain why | Second Short | Newsletter 01", "Week 5 — Short: Prediction or understanding? | Prototype the Prediction vs Explanation experience", "Week 6 — Video 03: Where does literature review with AI become dangerous? | Second Short | Citation Check dossier"], outcome: "Output by the end of week six: three videos, nine Shorts, two dossiers, one newsletter, and an initial behavioral baseline." },
    "تقویم انتشار؛ شش هفته‌ی دوم": { eyebrow: "12-Week Calendar / Weeks 7–12", title: "Publishing calendar: second six weeks", items: ["Week 7 — Short: Can AI review a paper? | First online session | Script Episode 4", "Week 8 — Video 04: Is peer review ready for the AI era? | Second Short | Newsletter 02 | Review-game beta", "Week 9 — Short: One common review mistake | Test the game with early users | Script Episode 5", "Week 10 — Video 05: Who gets left behind by the AI revolution in science? | Second Short | Scientific inequality map dossier", "Week 11 — Short: The real cost of scientific computing | Second online session | Script Episode 6", "Week 12 — Video 06: How do autonomous laboratories work? | Second Short | Newsletter 03 | Quarter review and next calendar"], outcome: "Output by the end of month three: six videos, eighteen Shorts, three dossiers, three newsletters, one interactive experience, and a clear decision for the next quarter." },
    "هر محتوا از این مسیر عبور می‌کند": { eyebrow: "Production System", title: "Every piece of content moves through this system", footer: "Editorial owns the final decision; production owns visuals and editing; Product/Growth owns the website, distribution, and data." },
    "مایل‌استون‌های تجمعی سه ماه اول": { eyebrow: "Milestones / Months 1–3", title: "Cumulative milestones for the first three months", items: ["Month 1 — 2 videos, 6 Shorts, 1 dossier, 1 newsletter, a four-week calendar, and KPI baselines", "Month 1 — Two initial offers, a target-customer list, and one proposal template", "Month 2 — 4 videos total, 12 Shorts, 2 dossiers, 2 newsletters, and the first community session", "Month 2 — Three qualified proposals and one workshop or small pilot", "Month 3 — 6 videos total, 18 Shorts, 3 dossiers, 3 newsletters, and one interactive experience", "Month 3 — First paid project, Decision Document, and selection of the two strongest content formats"], outcome: "Month-three gate: a promising format, signs of participation, sustainable production capacity, and at least one real sale should all be visible." },
    "مایل‌استون‌های تجمعی سه ماه دوم": { eyebrow: "Milestones / Months 4–6", title: "Cumulative milestones for months four to six", items: ["Month 4 — 8 videos, 24 Shorts, 4 dossiers, 4 newsletters, 800 newsletter subscribers, and 50 active members", "Month 4 — Second project, €5,000 cumulative revenue, and Membership Beta with 15 members", "Month 5 — 10 videos, 30 Shorts, 5 dossiers, 5 newsletters, and 75 active members", "Month 5 — Third project, €10,000 revenue, and testing an experiment-kit prototype", "Month 6 — 12 videos, 36 Shorts, 6 dossiers, 6 newsletters, two interactive experiences, and 500 MEP", "Month 6 — €15,000 in revenue or contracts, 50 paid members, and selection of two or three revenue engines for the next cycle"], outcome: "These numbers are the end-of-cycle KRs; the roadmap only shows the cumulative path toward them." },
    "سه نقطه‌ی تصمیم": { eyebrow: "Decision Gates", title: "Three decision points", items: [{ label: "End of week 2", text: "Are the real workflow, owners, production timing, and measurement tools working?" }, { label: "End of month 3", text: "Which topics and formats should be kept, changed, or stopped, and what evidence should shape the next three-month calendar?" }, { label: "End of month 5", text: "Among projects, education, membership, games, licensing, and kits, only evidence-backed paths should be selected for scale." }] },

    "انگلیسی، زبان پایه‌ی محتوا": { eyebrow: "Long-term Direction", title: "English is the primary content language", paragraphs: ["Gravitas produces its core content in English from the beginning so the project is connected immediately to the global conversation around science, technology, and philosophy.", "Persian and other languages are added based on audience need, team capacity, local partners, and content performance. Subtitles, adaptations, and localized editions each have a distinct role.", "For Gravitas, becoming multilingual means preserving one shared identity while designing an experience that fits each community—not mechanically translating one fixed output."] },
    "روایت. ابزار. فلسفه. بازی. جامعه.": { eyebrow: "Direction", title: "Story. Tools. Philosophy. Games. Community.", paragraphs: ["YouTube introduces people to Gravitas.", "The website lets them go deeper.", "Games bring the audience into the experience.", "Community creates a reason to return."], quote: "Gravitas is a place to see science, experience it, and think with others." }
  };

  function merge(base, override) {
    if (override === undefined) return clone(base);
    if (Array.isArray(base) && Array.isArray(override)) {
      if (base.some(item => item && typeof item === "object") && override.some(item => item && typeof item === "object")) {
        return base.map((item, index) => merge(item, override[index]));
      }
      return clone(override);
    }
    if (base && typeof base === "object" && !Array.isArray(base) && override && typeof override === "object" && !Array.isArray(override)) {
      const result = clone(base);
      Object.keys(override).forEach(key => { result[key] = merge(base[key], override[key]); });
      return result;
    }
    return clone(override);
  }

  const persianSlides = Array.isArray(window.GRAVITAS_SLIDES) ? clone(window.GRAVITAS_SLIDES) : [];
  const englishSlides = persianSlides.map(slide => {
    const translated = EN[slide.title];
    if (!translated) {
      if (hasPersian(JSON.stringify(slide))) console.warn("Missing English translation for slide:", slide.title);
      return clone(slide);
    }
    return merge(slide, translated);
  });

  window.GRAVITAS_SLIDES_FA = persianSlides;
  window.GRAVITAS_SLIDES_EN = englishSlides;
  window.GRAVITAS_SLIDES = language === "fa" ? clone(persianSlides) : clone(englishSlides);
  window.GRAVITAS_I18N = { language, chapters: clone(chapters[language]), strings: clone(strings[language]), allStrings: strings, storageKey: STORAGE_KEY };

  const ui = strings[language];
  document.documentElement.lang = language;
  document.documentElement.dir = language === "fa" ? "rtl" : "ltr";
  document.body.dataset.lang = language;

  const setText = (selector, text) => { const el = document.querySelector(selector); if (el) el.textContent = text; };
  const setAttr = (selector, attr, value) => { const el = document.querySelector(selector); if (el) el.setAttribute(attr, value); };

  setText(".skip-link", ui.skip);
  setAttr(".brand", "aria-label", ui.goCover);
  setAttr(".brand__mark img", "alt", ui.logoAlt);
  setText("#commentsButton span", ui.comments);
  setAttr("#printButton", "aria-label", ui.print);
  setAttr("#printButton", "title", ui.printTitle);
  setText("#indexButton span", ui.index);
  setAttr("#chapterRail", "aria-label", ui.chaptersLabel);
  setAttr(".deck-nav", "aria-label", ui.slideControls);
  setAttr("#prevButton", "aria-label", ui.previousAria);
  setAttr("#nextButton", "aria-label", ui.nextAria);
  setText(".index-panel__head h2", ui.indexTitle);
  setAttr("#indexClose", "aria-label", ui.closeIndex);
  const summaries = document.querySelectorAll(".index-summary span");
  if (summaries[0]) summaries[0].textContent = ui.summary1;
  if (summaries[1]) summaries[1].textContent = ui.summary2;
  if (summaries[2]) summaries[2].textContent = ui.summary3;
  const foot = document.querySelectorAll(".index-panel__foot span");
  if (foot[0]) foot[0].textContent = ui.arrowHelp;
  if (foot[1]) foot[1].textContent = ui.swipeHelp;
  setText(".comments-panel__head h2", ui.commentsTitle);
  setAttr("#commentsClose", "aria-label", ui.closeComments);
  setText(".comments-intro p", ui.commentsIntro);
  const fallback = document.querySelector(".comments-fallback");
  if (fallback) {
    const link = fallback.querySelector("a");
    fallback.childNodes.forEach(node => { if (node.nodeType === Node.TEXT_NODE) node.textContent = ""; });
    fallback.insertBefore(document.createTextNode(ui.commentsFallbackBefore), link || null);
    if (link) link.textContent = ui.commentsFallbackLink;
    fallback.appendChild(document.createTextNode(ui.commentsFallbackAfter));
  }
  setText(".noscript", ui.noScript);

  const switcher = document.getElementById("languageSwitch");
  if (switcher) {
    const label = switcher.querySelector("span");
    const code = switcher.querySelector("b");
    if (label) label.textContent = ui.languageTarget;
    if (code) code.textContent = ui.languageCode;
    switcher.setAttribute("aria-label", language === "fa" ? "Switch to English" : "تغییر زبان به فارسی");
    switcher.addEventListener("click", () => {
      localStorage.setItem(STORAGE_KEY, language === "fa" ? "en" : "fa");
      location.reload();
    });
  }

  const description = document.querySelector('meta[name="description"]');
  if (description) description.content = language === "fa"
    ? "نقشه‌ی راه توسعه‌ی Gravitas؛ رسانه، وب‌سایت، بازی‌های علمی و جامعه‌ای برای فهم عمیق‌تر علم."
    : "The Gravitas development roadmap: science media, website, games, research, and community.";
})();